# Generated by Django 3.1.3 on 2020-11-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='descuento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numdefactura', models.IntegerField(max_length=43)),
                ('nombre', models.CharField(max_length=40)),
                ('infdefactura', models.CharField(max_length=64)),
                ('usuario', models.CharField(max_length=45)),
                ('clave', models.IntegerField(max_length=25)),
            ],
        ),
    ]
