# Generated by Django 3.1.3 on 2020-11-27 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_pago', models.IntegerField(max_length=43)),
                ('forma_de_pago', models.CharField(max_length=40)),
                ('num_de_operacion', models.CharField(max_length=64)),
                ('tipo_de_cuenta', models.CharField(max_length=45)),
                ('monto', models.IntegerField(max_length=25)),
                ('descuento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicaweb.descuento')),
            ],
        ),
    ]
