# Generated by Django 3.1.3 on 2020-11-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaweb', '0002_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField(max_length=43)),
                ('direccion', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=45)),
                ('sexo', models.CharField(max_length=20)),
                ('ciudad', models.IntegerField(max_length=43)),
                ('estado', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='descuento',
            name='clave',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_de_pago',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='forma_de_pago',
            field=models.CharField(max_length=50, verbose_name='Forma de pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='pago',
            name='num_de_operacion',
            field=models.IntegerField(max_length=64),
        ),
    ]
