# Generated by Django 3.1.3 on 2020-11-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaweb', '0002_auto_20201128_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicio_factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_de_factura', models.CharField(max_length=43)),
                ('numdefacrura', models.IntegerField(max_length=40)),
                ('fecha_de_corte', models.DateField(null=True)),
                ('fecha_de_pago', models.DateField(null=True)),
                ('descripcion_fac', models.CharField(max_length=54)),
            ],
        ),
    ]
