# Generated by Django 3.1.3 on 2020-11-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaweb', '0003_servicio_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='tarjeta_de_credito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_tarjeta', models.CharField(choices=[('C', 'CREDITO'), ('D', 'DEBITO')], max_length=1)),
                ('fecha_de_vencimiento', models.DateField(null=True)),
                ('plazo', models.IntegerField(max_length=64)),
                ('num_de_cuenta', models.IntegerField(max_length=8, verbose_name='Numero_de_cuenta')),
                ('disponible', models.CharField(choices=[('S', 'SI'), ('N', 'NO')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='servicio_factura',
            name='numdefacrura',
        ),
        migrations.AddField(
            model_name='servicio_factura',
            name='num_defacrura',
            field=models.CharField(default='error', max_length=40),
            preserve_default=False,
        ),
    ]
