# Generated by Django 3.1.3 on 2020-11-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaweb', '0004_auto_20201127_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='tarjeta_de_credito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_tarjeta', models.IntegerField(max_length=50)),
                ('fecha_de_vencimiento', models.CharField(max_length=40)),
                ('plazo', models.CharField(max_length=64)),
                ('num_de_cuenta', models.IntegerField()),
                ('disponible', models.CharField(max_length=35)),
            ],
        ),
    ]
