# Generated by Django 3.1.3 on 2020-11-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaweb', '0006_servicio_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='descuento',
        ),
        migrations.AlterField(
            model_name='servicio_factura',
            name='fecha_de_corte',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='servicio_factura',
            name='fecha_de_pago',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tarjeta_de_credito',
            name='disponible',
            field=models.CharField(choices=[('S', 'SI'), ('N', 'NO')], max_length=1),
        ),
        migrations.AlterField(
            model_name='tarjeta_de_credito',
            name='fecha_de_vencimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tarjeta_de_credito',
            name='num_de_cuenta',
            field=models.IntegerField(max_length=8, verbose_name='Numero de cuenta'),
        ),
        migrations.AlterField(
            model_name='tarjeta_de_credito',
            name='plazo',
            field=models.IntegerField(max_length=64),
        ),
        migrations.AlterField(
            model_name='tarjeta_de_credito',
            name='tipo_de_tarjeta',
            field=models.CharField(choices=[('C', 'CREDITO'), ('D', 'DEBITO')], max_length=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=15),
        ),
    ]
