# Generated by Django 3.1.3 on 2020-11-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaweb', '0007_auto_20201127_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha_de_pago',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
