# Generated by Django 3.1.3 on 2020-11-27 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaweb', '0008_auto_20201127_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='fecha_de_pago',
        ),
    ]
