# Generated by Django 3.1.3 on 2020-11-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaweb', '0009_remove_pago_fecha_de_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='fecha_de_pago',
            field=models.DateField(null=True),
        ),
    ]
