# Generated by Django 3.1.3 on 2020-11-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaweb', '0010_pago_fecha_de_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='forma_de_pago',
            field=models.CharField(max_length=50, verbose_name='Forma_de_pago'),
        ),
    ]
